### ISSUE TITLE
npm install did not work for nodejs 10 or 11 on ubuntu 18.10 64bit

### ISSUE THREAD

**Issue by v217** [bsansouci/bucklescript#2]
Here is the log
npm install -g bsb-native

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '-g', 'bsb-native' ]
    2 info using npm@6.4.1
    3 info using node@v10.13.0
    4 verbose npm-session dd969accdb1340af
    5 silly install loadCurrentTree
    6 silly install readGlobalPackageData
    7 http fetch GET 304 https://registry.npmjs.org/bsb-native 1003ms (from cache)
    8 silly pacote tag manifest for bsb-native@latest fetched in 1017ms
    9 timing stage:loadCurrentTree Completed in 1186ms
    10 silly install loadIdealTree
    11 silly install cloneCurrentTreeToIdealTree
    12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
    13 silly install loadShrinkwrap
    14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
    15 silly install loadAllDepsIntoIdealTree
    16 silly resolveWithNewModule bsb-native@4.0.9 checking installable status
    17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 6ms
    18 timing stage:loadIdealTree Completed in 10ms
    19 silly currentTree lib
    20 silly idealTree lib
    20 silly idealTree └── bsb-native@4.0.9
    21 silly install generateActionsToTake
    22 timing stage:generateActionsToTake Completed in 4ms
    23 silly diffTrees action count 1
    24 silly diffTrees add bsb-native@4.0.9
    25 silly decomposeActions action count 8
    26 silly decomposeActions fetch bsb-native@4.0.9
    27 silly decomposeActions extract bsb-native@4.0.9
    28 silly decomposeActions preinstall bsb-native@4.0.9
    29 silly decomposeActions build bsb-native@4.0.9
    30 silly decomposeActions install bsb-native@4.0.9
    31 silly decomposeActions postinstall bsb-native@4.0.9
    32 silly decomposeActions finalize bsb-native@4.0.9
    33 silly decomposeActions refresh-package-json bsb-native@4.0.9
    34 silly install executeActions
    35 silly doSerial global-install 8
    36 verbose correctMkdir /home/v/.npm/_locks correctMkdir not in flight; initializing
    37 verbose lock using /home/v/.npm/_locks/staging-4ec0944d8e43c7e0.lock for /home/v/.npm-global/lib/node_modules/.staging
    38 silly doParallel extract 1
    39 silly extract bsb-native@4.0.9
    40 silly tarball trying bsb-native@latest by hash: sha512-Ghp6968bxnSE7/5OLxhlszFGtiVhcBzE2LV8NkTSzP2Qoq6UCcvNrFXu4kNRRYfwx0NyJh/MfF33XsWsvwQghA==
    41 silly extract bsb-native@latest extracted to /home/v/.npm-global/lib/node_modules/.staging/bsb-native-f0d2241f (24ms)
    42 timing action:extract Completed in 27ms
    43 silly doReverseSerial unbuild 8
    44 silly doSerial remove 8
    45 silly doSerial move 8
    46 silly doSerial finalize 8
    47 silly finalize /home/v/.npm-global/lib/node_modules/bsb-native
    48 timing action:finalize Completed in 3ms
    49 silly doParallel refresh-package-json 1
    50 silly refresh-package-json /home/v/.npm-global/lib/node_modules/bsb-native
    51 timing action:refresh-package-json Completed in 13ms
    52 silly doParallel preinstall 1
    53 silly preinstall bsb-native@4.0.9
    54 info lifecycle bsb-native@4.0.9~preinstall: bsb-native@4.0.9
    55 timing action:preinstall Completed in 2ms
    56 silly doSerial build 8
    57 silly build bsb-native@4.0.9
    58 info linkStuff bsb-native@4.0.9
    59 silly linkStuff bsb-native@4.0.9 has /home/v/.npm-global/lib/node_modules as its parent node_modules
    60 silly linkStuff bsb-native@4.0.9 is part of a global install
    61 silly linkStuff bsb-native@4.0.9 is installed into a global node_modules
    62 silly linkStuff bsb-native@4.0.9 is installed into the top-level global node_modules
    63 verbose linkBins [ { bsb: 'lib/bsb', bsc: 'lib/bsc', bsrefmt: 'lib/bsrefmt' },
    63 verbose linkBins   '/home/v/.npm-global/bin',
    63 verbose linkBins   true ]
    64 timing action:build Completed in 6ms
    65 silly doSerial global-link 8
    66 silly doParallel update-linked 0
    67 silly doSerial install 8
    68 silly install bsb-native@4.0.9
    69 info lifecycle bsb-native@4.0.9~install: bsb-native@4.0.9
    70 timing action:install Completed in 2ms
    71 silly doSerial postinstall 8
    72 silly postinstall bsb-native@4.0.9
    73 info lifecycle bsb-native@4.0.9~postinstall: bsb-native@4.0.9
    74 verbose lifecycle bsb-native@4.0.9~postinstall: unsafe-perm in lifecycle true
    75 verbose lifecycle bsb-native@4.0.9~postinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/v/.npm-global/lib/node_modules/bsb-native/node_modules/.bin:/home/v/.npm-global/lib/node_modules/.bin:/home/v/.opam/4.02.3+buckle-master/bin:/home/v/.npm-global/bin/:/home/v/.npm-global/bin/:/home/v/.npm-global/bin/:/home/v/.opam/default/bin:/home/v/.npm-global/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/v/.local/bin/
    76 verbose lifecycle bsb-native@4.0.9~postinstall: CWD: /home/v/.npm-global/lib/node_modules/bsb-native
    77 silly lifecycle bsb-native@4.0.9~postinstall: Args: [ '-c', 'node postinstall.js' ]
    78 silly lifecycle bsb-native@4.0.9~postinstall: Returned: code: 1  signal: null
    79 info lifecycle bsb-native@4.0.9~postinstall: Failed to exec postinstall script
    80 timing action:postinstall Completed in 92ms
    81 verbose unlock done using /home/v/.npm/_locks/staging-4ec0944d8e43c7e0.lock for /home/v/.npm-global/lib/node_modules/.staging
    82 timing stage:rollbackFailedOptional Completed in 5ms
    83 timing stage:runTopLevelLifecycles Completed in 1359ms
    84 verbose stack Error: bsb-native@4.0.9 postinstall: `node postinstall.js`
    84 verbose stack Exit status 1
    84 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
    84 verbose stack     at EventEmitter.emit (events.js:182:13)
    84 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    84 verbose stack     at ChildProcess.emit (events.js:182:13)
    84 verbose stack     at maybeClose (internal/child_process.js:962:16)
    84 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
    85 verbose pkgid bsb-native@4.0.9
    86 verbose cwd /home/v
    87 verbose Linux 4.18.0-11-generic
    88 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "bsb-native"
    89 verbose node v10.13.0
    90 verbose npm  v6.4.1
    91 error code ELIFECYCLE
    92 error errno 1
    93 error bsb-native@4.0.9 postinstall: `node postinstall.js`
    93 error Exit status 1
    94 error Failed at the bsb-native@4.0.9 postinstall script.
    94 error This is probably not a problem with npm. There is likely additional logging output above.
    95 verbose exit [ 1, true ]

**Comment by bsansouci** [comment]
Hey sorry about that, there's a missing dep on yauzl for some reason in 4.0.9. I'll fix it when I get home tonight!

**Comment by v217** [comment]
Great! Thanks!

**Comment by bsansouci** [comment]
Hey we just pushed 4.0.7000 (which is > than 4.0.9 and looks closer to bsb’s Version number), does it work?

**Comment by v217** [comment]
Sure! Thanks! I am really convinced that the new reasonml syntax is a big improvement for opam/native workflows as well. I think reasonml is on the syntax level a practical and immediately useful realization of ideas stated in https://github.com/rossberg/1ml.
